language: c
addons:
  apt:
    packages:
      - libxfixes-dev
      - mesa-common-dev
      - libgl1-mesa-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
compiler:
  - clang
  - gcc

matrix:
  include:
    - name: "Examples-release-rasberry-cross"
      language: c
      compiler: gcc
      before_install:
        - pushd /tmp
        - wget https://github.com/raspberrypi/tools/archive/master.tar.gz -O raspi-tools.tar.gz
        - tar xzf raspi-tools.tar.gz
        - wget https://github.com/raspberrypi/firmware/archive/master.tar.gz -O raspi-firmware.tar.gz
        - tar xzf raspi-firmware.tar.gz
        - popd
      script: make RASPBERRY=1 CROSS=1 RPI_TOOLS=/tmp/tools-master RPI_VCDIR=/tmp/firmware-master/hardfp/opt/vc examples
    - name: "Examples-release-win64"
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017" -A x64 ..
        - cmake --build . --config Release
    - name: "Examples-release-win32"
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017" -A Win32 ..
        - cmake --build . --config Release
