#version 460
#extension GL_EXT_ray_tracing : require

//layout(binding = 0, set = 0, rgba32f) uniform image2D image;
layout(binding = 0, set = 0, rgba8) uniform image2D image;

void main() {
//const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
  //const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
	
	vec3 c = vec3(fract(gl_LaunchIDEXT.xy / 10.), 1.);
  imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(c, 1.0));
}

